version: '3.1'

services:
  rabbit:
    image: "rabbitmq:3.11.22-management"
    restart: "always"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: scanner
      RABBITMQ_DEFAULT_PASS: scanner
      RABBITMQ_DEFAULT_VHOST: /

  rabbit_loader:
    build:
      context: .
      dockerfile: pybench/Dockerfile
    image: "rabbit_loader"
    restart: "no"
    depends_on:
      - "rabbit"
    environment:
      - PYTHONUNBUFFERED=1
    entrypoint: ./wait-for-it.sh -h rabbit -p 5672 -t 0 --
    command:
      - "python3"
      - "mongo_writer/writer_history_logs.py"
